# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys

class TestGroupcreation():

    driver = webdriver.Chrome(ChromeDriverManager().install())
    driver.get("http://localhost/addressbook/index.php")
    driver.set_window_size(1920, 977)
    user = driver.find_element_by_name("user")
    user.send_keys("admin")
    driver.find_element_by_name("pass").send_keys('secret')
    driver.find_element_by_xpath("/html/body/div/div[4]/form/input[3]").click()
    driver.find_element_by_link_text("groups").click()
    driver.find_element(By.NAME, "new").click()
    driver.find_element(By.NAME, "group_name").click()
    driver.find_element(By.NAME, "group_name").send_keys("Test2_name")
    driver.find_element(By.NAME, "group_header").click()
    driver.find_element(By.NAME, "group_header").send_keys("Test2_header")
    driver.find_element(By.NAME, "group_footer").click()
    driver.find_element(By.NAME, "group_footer").send_keys("Test2_footer")
    driver.find_element(By.NAME, "submit").click()
    driver.find_element(By.LINK_TEXT, "groups").click()
    driver.close()
